# Generated by Django 5.0.2 on 2024-02-21 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0002_shop_shop_gst'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_address', models.CharField(max_length=100)),
                ('customer_contact', models.CharField(max_length=100)),
                ('customer_email', models.CharField(max_length=100)),
                ('customer_gst', models.CharField(max_length=100)),
                ('customer_items', models.CharField(max_length=100)),
                ('customer_quantity', models.CharField(max_length=100)),
                ('customer_price', models.CharField(max_length=100)),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
        ),
    ]
