# Generated by Django 5.0.2 on 2024-02-23 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingInfo', '0001_initial'),
        ('shops', '0002_shop_shop_gst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginfo',
            name='shop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.shop'),
        ),
    ]
