# Generated by Django 5.0.2 on 2024-02-23 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billingInfo', '0002_alter_billinginfo_shop_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinginfo',
            name='customer_price',
        ),
        migrations.RemoveField(
            model_name='billinginfo',
            name='shop_id',
        ),
    ]
