# Generated by Django 5.0.2 on 2024-02-23 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingInfo', '0003_remove_billinginfo_customer_price_and_more'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginfo',
            name='customer_items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cart.cartmodels'),
        ),
    ]
