# Generated by Django 5.0.2 on 2024-02-23 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0002_shop_shop_gst'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellingItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.CharField(max_length=100)),
                ('item_price', models.CharField(max_length=100)),
                ('item_quantity', models.CharField(max_length=100)),
                ('item_category', models.CharField(max_length=100)),
                ('item_shop', models.CharField(max_length=100)),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.shop')),
            ],
        ),
    ]
