# Generated by Django 5.0.2 on 2024-02-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_address', models.CharField(max_length=100)),
                ('shop_contact', models.CharField(max_length=100)),
                ('shop_email', models.CharField(max_length=100)),
            ],
        ),
    ]
