# Generated by Django 5.0.2 on 2024-02-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_gst',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
