# Generated by Django 5.0.2 on 2024-02-23 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellingitems', '0002_remove_sellingitems_item_shop'),
        ('shops', '0002_shop_shop_gst'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('total_cost', models.FloatField(default=0.0)),
                ('added_items', models.ManyToManyField(to='sellingitems.sellingitems')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.shop')),
            ],
        ),
    ]
